
# 项目名称  npx wrangler deploy
name = "huzhihui"

# 兼容性日期
compatibility_date = "2025-06-25"

# 生产环境使用自定义域，不暴露 workers.dev / preview URLs
workers_dev = false
preview_urls = false

[[routes]]
pattern = "huzhihui.com"
custom_domain = true

[assets]
directory = "./out"
